name: Deploy new version

# Only deploy when a new tag is pushed
#on:
#    push:
#        tags:
#          - "v*.*.*"
on:
    workflow_call:          
# Must match the project() name in CMakeLists.txt
env:
    APP_NAME: zephyr
    
# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binary and send to releases
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        steps:
        
          - name: Check out this repository
            uses: actions/checkout@v3
            
          - name: Build Docker image
            run: docker build -t nrf-builder-image --build-arg sdk_nrf_version=v2.5-branch -f actions/DockerfileNrf .
            
          - name: Create Docker container
            run: docker create --name nrf-builder-container nrf-builder-image
            
          - name: Copy out .hex file
            run: docker cp nrf-builder-container:/workdir/project/build/zephyr/${APP_NAME}.hex ./${APP_NAME}.hex
            
          - name: Put environment variable into the env context
            run: echo "app_name=$APP_NAME" >> $GITHUB_ENV
            
          - name: Push to release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: ${{ env.app_name }}.hex
                body_path: CHANGELOG.md 
