name: allActions
on:
    push:
#        branches: [ "main" ]
    workflow_dispatch:
permissions:
    contents: write
jobs:
#    get-files:
#        runs-on: ubuntu-latest
#        steps:
#          - uses: actions/checkout@v3
    call-test:
        uses: ./.github/workflows/test.yml
    call-deploy:
        if: startsWith(github.ref, 'refs/tags/v')
        needs: call-test
        uses: ./.github/workflows/deploy.yml